name: Validar Script Shell

on:
  push:
    branches:
      - master  # Se ejecuta cada vez que se hace push a master

jobs:
  shellcheck:
    name: Validar con ShellCheck
    runs-on: ubuntu-latest

    steps:
      - name: Clonar el repositorio
        uses: actions/checkout@v3

      - name: Instalar ShellCheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Ejecutar ShellCheck en script.sh
        run: shellcheck script.sh
